# Generated by Django 4.2.4 on 2023-08-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0008_alter_userprofile_address_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
