# Generated by Django 4.2.4 on 2023-08-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0016_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
